version: 2.0
orbs:
  slack: circleci/slack@4.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    working_directory:  ~/ci
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0f:b3:05:30:eb:c4:f7:0d:aa:1e:9d:ff:e4:ad:ee:28"
      # Checkout the code as the first step.
      - checkout
      # Use mvn clean and package as the standard maven build phase
      - save_cache:
          key: 'dependencies-{{ checksum "pom.xml" }}'
          paths:
            - ~/.m2 
      - run:
          name: List all content from source code
          command: pwd && ls -la
      - run:
          name: Install dependencies
          command: mvn dependency:go-offline        
      - run:
          name: Validate
          command: mvn -B validate
      - run:
          name: Compile
          command: mvn -B compile                
      - run:
          name: Test
          command: mvn test
      - run:
          name: Check code coverage
          command: mvn clean test
      - run:
          name: Install
          command: mvn clean install
      - run:
          name: Validate WAR file
          command: pwd && ls -la ./target && chmod 755 ./target/LoginWebApp-1.war    
      - run:
          name: Deploy artifact to nexus
          command: |
            curl -u admin:fptproject -X GET 'http://13.215.61.77:8081/service/rest/v1/components?repository=test'
            curl -v -u admin:fptproject -X POST 'http://13.215.61.77:8081/service/rest/v1/components?repository=store-artifact' -F maven2.groupId=com.google.guava -F maven2.artifactId=guava -F maven2.version=24.0-jre -F maven2.asset1=/home/circleci/project/target/LoginWebApp-1.war -F maven2.asset1.extension=war      
      - run:
          name: Deploy to tomcat server over SSH
          command: |
            ls -la ./target
            scp -o "StrictHostKeyChecking=no" ./target/LoginWebApp-1.war ubuntu@ec2-54-151-223-91.ap-southeast-1.compute.amazonaws.com:/tmp
            ssh -o "StrictHostKeyChecking=no" ubuntu@ec2-54-151-223-91.ap-southeast-1.compute.amazonaws.com "sudo mv /tmp/LoginWebApp-1.war /opt/tomcat/webapps/ && pwd && sudo ls -la /opt/tomcat/webapps/"
      - slack/notify:
          event: fail
          channel: $SLACK_DEFAULT_CHANNEL
          template: basic_fail_1
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: pass
          template: success_tagged_deploy_1
      - run:
          name: Check workspace
          command: pwd && ls -la
  deploy:
    executor: machine
    steps:
      - attach_workspace:
          at: ~/ci
      - run: 
          name: Checking folder of build step
          command: cd /home/circleci/project && ls -la
      
# workflows:
#   build:
#     jobs:
#       - build:
#           filters:
#             branches:
#               only: sit

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: sit


